volumes:
    data_db:

services:
    # Webserver
    nginx:
        image: nginx:stable-alpine
        container_name: educa_nginx
        depends_on:
            - php
            - mysql
        ports:
            - 8000:80
        volumes:
            - ./src:/var/www/educa
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - educa_network

    # PHP
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: educa_php72
        depends_on:
            - mysql
        ports:
            - 9000:9000
        volumes:
            - ./src:/var/www/educa
        networks:
            - educa_network

    # Database
    mysql:
        image: mysql:8.0.27
        container_name: educa_mysql
        ports:
            - 3306:3306
        volumes:
            - data_db:/var/lib/mysql
            - ./docker/mysql/my.conf:/etc/mysql/conf.d/custom.cnf
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            # MYSQL_USER: ${MYSQL_USER}
            # MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        networks:
            - educa_network
    
    # PhpMyAdmin
    phpmyadmin:
        image: phpmyadmin
        container_name: educa_pma
        ports:
            - 8090:80
        environment:
            PMA_HOST: mysql
        depends_on:
            - mysql
        networks:
            - educa_network
  
networks:
    educa_network:
        driver: bridge
